// <auto-generated />
using ControleJogos.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ControleJogos.Migrations
{
    [DbContext(typeof(ControleJogosContext))]
    [Migration("20180201012136_Emprestimo")]
    partial class Emprestimo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControleJogos.Model.Amigo", b =>
                {
                    b.Property<int>("AmigoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Telefone");

                    b.HasKey("AmigoID");

                    b.ToTable("Amigos");
                });

            modelBuilder.Entity("ControleJogos.Model.Emprestimo", b =>
                {
                    b.Property<int>("EmprestimoID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataDevolucao");

                    b.Property<DateTime>("DataDevolucaoPrevista");

                    b.Property<DateTime>("DataEmprestimo");

                    b.HasKey("EmprestimoID");

                    b.ToTable("Emprestimo");
                });

            modelBuilder.Entity("ControleJogos.Model.EmprestimoJogo", b =>
                {
                    b.Property<int>("JogoID");

                    b.Property<int>("EmprestimoID");

                    b.HasKey("JogoID", "EmprestimoID");

                    b.HasIndex("EmprestimoID");

                    b.ToTable("EmprestimoJogo");
                });

            modelBuilder.Entity("ControleJogos.Model.Jogo", b =>
                {
                    b.Property<int>("JogoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Foto");

                    b.Property<int>("Quantidade");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("JogoID");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("ControleJogos.Model.EmprestimoJogo", b =>
                {
                    b.HasOne("ControleJogos.Model.Emprestimo", "Emprestimo")
                        .WithMany("EmprestimoJogo")
                        .HasForeignKey("EmprestimoID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ControleJogos.Model.Jogo", "Jogo")
                        .WithMany("EmprestimoJogo")
                        .HasForeignKey("JogoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
