// <auto-generated />
using ControleJogos.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ControleJogos.Migrations
{
    [DbContext(typeof(ControleJogosContext))]
    partial class ControleJogosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControleJogos.Model.Amigo", b =>
                {
                    b.Property<int>("AmigoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Telefone");

                    b.HasKey("AmigoID");

                    b.ToTable("Amigos");
                });

            modelBuilder.Entity("ControleJogos.Model.Jogo", b =>
                {
                    b.Property<int>("JogoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Foto");

                    b.Property<int>("Quantidade");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("JogoID");

                    b.ToTable("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
